### ISSUE TITLE
LargeHotel no work

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio-Prototype-Buildings#56]
No space called Kitchen_ZN_1_FLR_1 was found in the model

**Comment by YixingChen** [comment]
I just tested the large hotel. It works. So please provide more information about your test (vintage, climate zone).

**Comment by brianlball** [comment]
Setting variable 'building_type' to LargeHotel",
"[19:35:55.228906 INFO] Setting variable 'building_vintage' to 90.1-2010",
"[19:35:55.229963 INFO] Setting variable 'climate_zone' to ASHRAE 169-2006-4A",

In all of them running on OS-Server I got the following error: No space called Kitchen_ZN_1_FLR_1 was found in the model"

Perhaps that space got added to the model in recent updates?
I'm using OS 1.8.5

**Comment by YixingChen** [comment]
I fix the bug. You can try it again from the master branch.

**Comment by brianlball** [comment]
With 1.9.0 I get a different error now (After your fix).  The measure doesnt finishing running on the server:

[16:16:31.971586 INFO] Setting variable 'building_type' to LargeHotel
[16:16:31.976363 INFO] Setting variable 'building_vintage' to 90.1-2010
[16:16:31.979626 INFO] Setting variable 'climate_zone' to ASHRAE 169-2006-2A
[16:16:31.984771 INFO] Calling measure.run for 'create_doe_prototype_building'
[16:17:40.089689 INFO] Finished measure.run for 'create_doe_prototype_building'
[16:17:40.097372 INFO] Running of measure 'create_doe_prototype_building' completed. Post-processing measure output
[16:17:40.101098 WARN] [openstudio.standards.ConstructionBase] Requested U-value of 1.45 for Typical Overhead Door is too low given the other materials in the construction; insulation layer will not be modified.
[16:17:40.107125 WARN] [openstudio.standards.Model] Find object search criteria returned 2 results, the first one will be returned. Called from /mnt/openstudio/analysis_0e930660-441b-4b58-b7e9-c97866b734cd/measures/create_DOE_prototype_building/resources/Standards.Model.rb:979:in `find_and_add_construction'. 
 Search criteria: 
 {"template"=>"90.1-2010", "climate_zone_set"=>"ClimateZone 2", "intended_surface_type"=>"Skylight", "standards_construction_type"=>"Glass with Curb", "building_category"=>"Nonresidential"} 
  All results: 
 {"template"=>"90.1-2010", "climate_zone_set"=>"ClimateZone 2", "intended_surface_type"=>"Skylight", "standards_construction_type"=>"Glass with Curb", "building_category"=>"Nonresidential", "construction"=>"U 1.98 SHGC 0.36 Sgl Ref-B-H Clr 6mm", "minimum_percent_of_surface"=>0.0, "maximum_percent_of_surface"=>2.0, "assembly_maximum_u_value"=>1.98, "assembly_maximum_f_factor"=>nil, "assembly_maximum_c_factor"=>nil, "assembly_maximum_solar_heat_gain_coefficient"=>0.36, "assembly_minimum_vt_shgc"=>nil, "sort_order"=>2579.0}
{"template"=>"90.1-2010", "climate_zone_set"=>"ClimateZone 2", "intended_surface_type"=>"Skylight", "standards_construction_type"=>"Glass with Curb", "building_category"=>"Nonresidential", "construction"=>"U 1.98 SHGC 0.19 Simple Glazing Skylight", "minimum_percent_of_surface"=>2.001, "maximum_percent_of_surface"=>100.0, "assembly_maximum_u_value"=>1.98, "assembly_maximum_f_factor"=>nil, "assembly_maximum_c_factor"=>nil, "assembly_maximum_solar_heat_gain_coefficient"=>0.19, "assembly_minimum_vt_shgc"=>nil, "sort_order"=>2580.0}
[16:17:40.112510 WARN] [openstudio.standards.Model] Find object search criteria returned 2 results, the first one will be returned. Called from /mnt/openstudio/analysis_0e930660-441b-4b58-b7e9-c97866b734cd/measures/create_DOE_prototype_building/resources/Standards.Model.rb:979:in `find_and_add_construction'. 
 Search criteria: 
 {"template"=>"90.1-2010", "climate_zone_set"=>"ClimateZone 2", "intended_surface_type"=>"Skylight", "standards_construction_type"=>"Glass with Curb", "building_category"=>"Nonresidential"} 
  All results: 
 {"template"=>"90.1-2010", "climate_zone_set"=>"ClimateZone 2", "intended_surface_type"=>"Skylight", "standards_construction_type"=>"Glass with Curb", "building_category"=>"Nonresidential", "construction"=>"U 1.98 SHGC 0.36 Sgl Ref-B-H Clr 6mm", "minimum_percent_of_surface"=>0.0, "maximum_percent_of_surface"=>2.0, "assembly_maximum_u_value"=>1.98, "assembly_maximum_f_factor"=>nil, "assembly_maximum_c_factor"=>nil, "assembly_maximum_solar_heat_gain_coefficient"=>0.36, "assembly_minimum_vt_shgc"=>nil, "sort_order"=>2579.0}
{"template"=>"90.1-2010", "climate_zone_set"=>"ClimateZone 2", "intended_surface_type"=>"Skylight", "standards_construction_type"=>"Glass with Curb", "building_category"=>"Nonresidential", "construction"=>"U 1.98 SHGC 0.19 Simple Glazing Skylight", "minimum_percent_of_surface"=>2.001, "maximum_percent_of_surface"=>100.0, "assembly_maximum_u_value"=>1.98, "assembly_maximum_f_factor"=>nil, "assembly_maximum_c_factor"=>nil, "assembly_maximum_solar_heat_gain_coefficient"=>0.19, "assembly_minimum_vt_shgc"=>nil, "sort_order"=>2580.0}
[16:17:40.115200 WARN] [openstudio.model.Space] For Banquet_Flr_6, could not determine VLT for U 0.72 SHGC 0.25 SGL REF-B-M TINT 6MM, will not be included in sidelighting effective aperture caluclation.
[16:17:40.116732 WARN] [openstudio.Standards.Space] Banquet_Flr_6 has no windows where VLT could be determined, sidelighting effective aperture will be higher than it should.
[16:17:40.120470 WARN] [openstudio.model.Space] For Dining_Flr_6, could not determine VLT for U 0.72 SHGC 0.25 SGL REF-B-M TINT 6MM, will not be included in sidelighting effective aperture caluclation.
[16:17:40.123325 WARN] [openstudio.Standards.Space] Dining_Flr_6 has no windows where VLT could be determined, sidelighting effective aperture will be higher than it should.
[16:17:40.124519 WARN] [openstudio.model.Space] For Cafe_Flr_1, could not determine VLT for U 0.72 SHGC 0.25 SGL REF-B-M TINT 6MM, will not be included in sidelighting effective aperture caluclation.
[16:17:40.128290 WARN] [openstudio.Standards.Space] Cafe_Flr_1 has no windows where VLT could be determined, sidelighting effective aperture will be higher than it should.
[16:17:40.130236 WARN] [openstudio.model.Space] For Lobby_Flr_1, could not determine VLT for U 0.72 SHGC 0.25 SGL REF-B-M TINT 6MM, will not be included in sidelighting effective aperture caluclation.
[16:17:40.131415 WARN] [openstudio.Standards.Space] Lobby_Flr_1 has no windows where VLT could be determined, sidelighting effective aperture will be higher than it should.
[16:17:40.132826 WARN] [openstudio.EpwFile] Successive data points (1987-Jan-31 to 1981-Feb-01, ending on line 753) are greater than 1 day apart in EPW file '/mnt/openstudio/analysis_0e930660-441b-4b58-b7e9-c97866b734cd/measures/create_DOE_prototype_building/resources/USA_TX_Houston-Bush.Intercontinental.AP.722430_TMY3.epw'. Data will be treated as typical (TMY)
[16:17:40.137059 ERROR] [openstudio.Standards.Space] Model has no sql file containing results, cannot lookup data.
[16:17:40.138636 ERROR] [openstudio.Standards.Space] Model has no sql file containing results, cannot lookup data.
[16:17:40.140350 ERROR] [openstudio.Standards.Space] Model has no sql file containing results, cannot lookup data.
[16:17:40.144495 ERROR] [openstudio.Standards.Space] Model has no sql file containing results, cannot lookup data.

**Comment by brianlball** [comment]
I get the same error running in OS-app 1.9.0

**Comment by brianlball** [comment]
and this error for large hotel:

Unable to find Exhaust Schedule for space type DOE Ref 1980-2004-LargeHotel-Banquet",

**Comment by YixingChen** [comment]
@brianlball those errors are actually fake errors. The model should be able to run and generate results. I will check with the team to clean up the errors.

**Comment by brianlball** [comment]
still seeing these errors with 1.9.1:
 
Error: Unable to find Exhaust Schedule for space type DOE Ref Pre-1980-LargeHotel-Banquet"

Error: Unable to find Exhaust Schedule for space type DOE Ref 1980-2004-LargeHotel-Banquet

**Comment by YixingChen** [comment]
The exhaust schedule bug is fixed.

**Comment by brianlball** [comment]
yep, looks good thanks
