### ISSUE TITLE
RetailStripMall / warehouse no work

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio-Prototype-Buildings#60]
failed with wrong number of arguments (3 for 4..7), /mnt/openstudio/analysis_33f62456-415e-4b32-8fa0-b919c98050fa/measures/create_DOE_prototype_building/resources/Prototype.hvac_systems.rb:814:in `add_psz_ac'/mnt/openstudio/analysis_33f62456-415e-4b32-8fa0-b919c98050fa/measures/create_DOE_prototype_building/resources/Prototype.retail_stripmall.rb:53

failed with wrong number of arguments (3 for 4..7), /mnt/openstudio/analysis_33f62456-415e-4b32-8fa0-b919c98050fa/measures/create_DOE_prototype_building/resources/Prototype.hvac_systems.rb:814:in `add_psz_ac'/mnt/openstudio/analysis_33f62456-415e-4b32-8fa0-b919c98050fa/measures/create_DOE_prototype_building/resources/Prototype.warehouse.rb:61

**Comment by YixingChen** [comment]
Currently, the measure can create OSM for small hotel, large hotel, standalone retail, small office, secondary school, primary school, and medium office. The other building types will come on later.

**Comment by brianlball** [comment]
Lets not close this issue until the measure creates the building
